### ISSUE TITLE
Instructor Feedback Week 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Amatheia/IndividualProject#1]
You are off to a great start. The screen design shows you've put a lot of thought into this project already.  

- [ ] If this will be a Spring project, consider starting with Spring right away, as opposed to adding it in later. Previous students recommend this approach; those who tried to add the Spring framework in later generally ended up creating a brand new Spring project and had to copy their existing work over. 
- [ ] If you are using Angular and Groovy, that would be plenty of independent research without tackling  Spring. You can absolutely do all three, but I just want to make sure we size this right for you!

**Comment by Amatheia** [comment]
Thanks! Definitely something to think about and decide on this week :)
