### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by glenndog** [Amatheia/IndividualProject#3]
# Design/Code Review 1

#### Reviewer: Glenn Childs

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Problem Statement**|Does it exist?|yes|
| |Does the problem statement accurately describe project purpose?|yes, concise statement and solution. One thing it could use is a name for the app.|
| |Is the problem statement professional? Think of prospective employers viewing this as part of the developer's portfolio.|Yes, well done.|
| |What is good?|short and to the point|
| |What could be improved?| Name the app.  |
|**Design Documentation**|Does it exist?| yes |
| |Is the navigation/flow through the application logical and easy to use?| yes makes sense . I like the dashboard page. |
| |Is the order in which the fields are displayed and form fields entered logical and easy to use?| yes |
| |What data is missing?| maybe a report? weekly? monthly? Features for v 2.0... |
| |Is there data that is not used?| not apparent  |
| |What is good?| simplicity is good |
| |What could be improved?| Not necessary for the function but a suggestion about usability: add a page that lets a user quickly adjust the inventory levels of each item, just a simple big button with a + or -  may make it quicker to keep on top of inventory changes.  |
|**Data model**|Does it exist?| yes |
| |Is everything on the screens represented in the model?| Seems to be, but I would not have products attached to users. Have products belong to an organizational unit (like warehouse, or call it 'cooler' or 'storage', and then users belong to the org unit. THis way multiple users can use the same inventory. As it's set up now, every user will need an instance of a product. Also, there will be a lot of repeating info in the product table. Vendor and category are examples. Product itself can be a look-up table How many basic types of foodstuffs are there? Ex: coffee, sugar, carrots, etc. What differentiates these commodities is the brand (vendor), and the price and so on. But coffee is coffee, carrots are carrots. They won't change.  |
| |Does the model represent good database design? | Needs further normalization.  |
| |What is good?| there is a good amount of info, it just needs to be normalized |
| |What could be better?| Add datatypes.  |
|**Additional design documents**| | |
|**Application structure in IntelliJ**|Does it exist?| yes |
| |Is the structure correct for a Maven project?| appears to be |
| |Are packages and classs appropriately named?   | yes |
| |Other comments/notes?| |
|**JSPs**|Do they exist?| yes |
| |Is templating used (for example, header.jsp, footer.jsp, etc.)?| yes |
| |Is there business logic mixed in the JSPs?| no |
| |CSS?| no |
| |Other comments/notes?| |
|**Entities/DAOs/Controllers**|Do they exist?| yes |
|**Java code quality**|Are methods single-purpose?|  |
| |Are classes appropriately-sized classes (no monster classes)?|  |
| |Are the same lines of code repeated at all?| | 
| |Do any classes perform very similar functions that could be candidates for super/subclass relationships?| |
| |Are any values hard-coded that should be in a properties file?| |
| |Are variable names descriptive?| |
| |Are there many branches or loops that could be simplified or broken up into smaller methods?| |
| |Do the DAOs use Hibernate? No hard-coded sql!| yes  |
| |Other comments/notes?| |
|**Logging**|Has log4J been added?| yes |
| |Are there logging statements in the code?| yes |
| |Are appropriate logging levels used? Info, debug, error, for example.| |
| |Are there any System.out.printlns in the code?| |
| |Other comments/notes?| |
|**Unit Tests**|Do they exist?| |
| |Do the tests pass?| |
| |What is the current code coverage?| |
| |Is each test truly a unit test or are they functional tests?| |
| |Other comments/notes?| |
|**Web Service/API integration**|Has a web service/api been selected? | don't think so |
| |What web services/apis might work well with this application?| RESTful w/ JSON |
|**Independent research topic**| Has a topic been selected?| don't think so |
| |What topic/s might fit well in this application?| |

**Comment by glenndog** [comment]
Sorry, don't know why markdown is broken, this works fine as a .md file on my machine.

**Comment by pawaitemadisoncollege** [comment]
I had the same issue - add a space between the pipes on the left hand side and that should fix it. || should be | |

**Comment by glenndog** [comment]
Spaces added, now it renders as it should.

**Comment by Amatheia** [comment]
Bootstrap :)
