### ISSUE TITLE
Review from Peter

### ISSUE THREAD

**Issue by pknibbe** [Amatheia/IndividualProject#5]
# Design/Code Review 2

#### Reviewer: Peter

|Category|Criteria|Analysis/Comments|
|--------|---------|---------------|
|**Running application**|| |
||Describe the application functionality that has been built and is working.| Front screen shows users and has a menu bar
 Each of the links takes me to a different screen that is pretty much set up. There are four entities, each with a DAO and servlets. |
||What is good?| It's looking pretty good right now. |
||What could be improved?| No issues |
|**Unit Tests**|| |
||What are the code coverage statistics?| Pretty low. Add is there. Don't see other DAO methods. | 
||Are @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code?| No. Also, the tests don't clean up after themselves | 
|**JSPs**|| |
|| Is templating used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.)| yes |
||What is good?| looks great |
||What could be improved?| don't know |
|**Code quality**|| |
||Are methods single-purpose?| seem to be. Too early to tell for sure. |
||Are classes appropriately-sized classes (no monster classes)?| yes |
||Are the same lines of code repeated at all?| not that I saw | 
||Do any classes perform very similar functions that could be candidates for super/subclass relationships?| Not that I saw |
||Are any values hard-coded that should be in a properties file?| Not that I saw |
||Are variable names descriptive?| Yes |
||Are there many branches or loops that could be simplified or broken up into smaller methods?| Not yet. |
||Do the DAOs use Hibernate? No hard-coded sql!| Hibernate |
||Has log4J been added?| yes |
||Are there logging statements in the code?| yes |
||Are appropriate logging levels used? Info, debug, error, for example.| yes |
||Are there any System.out.printlns in the code?| no |
||Other comments/notes?| method headers are there |
|**Web Service/API integration**|Which web service/api is being used? | none yet |
||Is the integration built?| |
|| If so, evaluate the integration code. What is good? What could use improvement?
|**Independent research topic**| What is the developer's independent research topic?| None yet |
||Has the topic been implemented in the project?| |
||If so, evaluate the implementation. What is good? What could use improvement?| |
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.| Better front-end form setup, better use of logging levels, better use of templating |

**Comment by pawaitemadisoncollege** [comment]
Can you update the formatting here - adding a space between the leading double pipes on each line should do it. || versus | |
