### ISSUE TITLE
Instructor Feedback Week 13

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Amatheia/IndividualProject#7]
- [x] Daos have some hard-coded data
- [x] Daos have some redundant code. Consider using an abstract dao rather than repeating methods like getAll, delete, update, add in each dao. Here is an [article and example code](https://www.ibm.com/developerworks/library/j-genericdao/).  Ignore the paragraphs with Spring, as those don't apply here. 
- [x] rather than using java in your pages like this: <%=c.getCategoryId()%> and <%
            CategoryDao categorylist = new CategoryDao();
            List<Category> list = categorylist.getAllCategories();
            for (Category c : list) {
        %>, use javabeans, jstl, and expression language (refer to project 4 advanced java or the sample application from the beginning of the semester)
- [x] Is your db design here somewhere? If not could you generate it and post? My question is this - is there a relationship between the Product and Category?  If so, annotate your entities to reflect this. Product should have an instance variable for Category.  Here is an [example which might help](https://www.mkyong.com/hibernate/hibernate-one-to-one-relationship-example-annotation/)

**Comment by Amatheia** [comment]
I took down the ERD because it needed updating. But the sql is posted here:
https://github.com/Amatheia/IndividualProject/blob/master/inventorytracker.sql

thanks!

**Comment by pawaitemadisoncollege** [comment]
Got it. Looks to me like there should be relationships between vendor and product and category and product?

**Comment by Amatheia** [comment]
Yes. :)

**Comment by Amatheia** [comment]
I think I have an idea for a generic dao, something like this:

public class Dao {

    private final Logger log = Logger.getLogger(this.getClass());

    private SessionFactory sessionFactory;

    public <T> List<T> getAll(final Class<T> type) {
        final Session session = sessionFactory.getCurrentSession();
        final Criteria crit = session.createCriteria(type);
        return crit.list();
    }

    public <T> T get(final Class<T> type, int id){
        return (T) sessionFactory.getCurrentSession().get(type, id);
    }

    public <T> T save(final T o){
        return (T) sessionFactory.getCurrentSession().save(o);
    }

    public void delete(final Object object){
        sessionFactory.getCurrentSession().delete(object);
    }

    public <T> void saveOrUpdate(final T o){
        sessionFactory.getCurrentSession().saveOrUpdate(o);
    }

}

Not sure how to add exception handling to this, though?

**Comment by pawaitemadisoncollege** [comment]
Looks like a great start!  Next, add a try/catch into each method for Hibernate Exceptions and any other Exception and log the error.  I’d also recommend throwing your own exception as part of the catch so that any callers can be notified of a problem in this layer. Does that make sense?

Paula

On Apr 19, 2017, at 11:14 PM, Amatheia <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I have an idea for a generic dao, something like this:

public class Dao {

private final Logger log = Logger.getLogger(this.getClass());

private SessionFactory sessionFactory;

public <T> List<T> getAll(final Class<T> type) {
    final Session session = sessionFactory.getCurrentSession();
    final Criteria crit = session.createCriteria(type);
    return crit.list();
}

public <T> T get(final Class<T> type, int id){
    return (T) sessionFactory.getCurrentSession().get(type, id);
}

public <T> T save(final T o){
    return (T) sessionFactory.getCurrentSession().save(o);
}

public void delete(final Object object){
    sessionFactory.getCurrentSession().delete(object);
}

public <T> void saveOrUpdate(final T o){
    sessionFactory.getCurrentSession().saveOrUpdate(o);
}


}

Not sure how to add exception handling to this, though?
